trigger:
  branches:
    include:
      - main
      - feature/testcontext-integration

pool:
  name: RestAPI-Service-vm-pool

steps:
- checkout: self
  displayName: 'Checkout code'

- task: UseJava@1
  inputs:
    versionSpec: '17'
    distribution: 'Temurin'
  displayName: 'Install JDK 17'

- script: mvn clean install
  displayName: 'Build project'

- script: mvn test -Dcucumber.filter.tags=@initial
  displayName: 'Run @initial tests'