parameters:
  - name: nameRegex
    type: string
    default: '.*_Teil1$'

trigger:
  branches:
    include:
      - main
      - demo_with_yml

pool:
  name: RestAPI-Service-vm-pool

variables:
  TEST_PROJECT_PATH: '$(Pipeline.Workspace)/Playwright Java Cucumber'
  artifactName: 'TestResults_$(parameters.tag)'


steps:
  - checkout: self
    displayName: 'Checkout code'

  - script: mvn --version
    displayName: 'Show Maven and Java version'

  - script: mvn clean install -DskipTests
    displayName: 'Build project'

  - script: |
      echo "Running scenarios matching name regex: ${{ parameters.nameRegex }}"
      mvn test -Dcucumber.filter.name="${{ parameters.nameRegex }}"
      displayName: 'Run Cucumber tests by name regex'

  - script: |
      echo Testprojektpfad: %TEST_PROJECT_PATH%
    displayName: 'Show TEST_PROJECT_PATH variable'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)/test-results/'
      artifact: '$(artifactName)'
      publishLocation: 'pipeline'