trigger:
  branches:
    include:
      - main
      - feature/testcontext-integration

pool:
  name: RestAPI-Service-vm-pool

steps:
- checkout: self
  displayName: 'Checkout code'
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Set up JDK 17'
- script: mvn -B test -Dcucumber.filter.tags=@initial
  displayName: 'Run tests with @initial tag'