trigger:
  branches:
    include:
      - main
      - feature/testcontext-integration

pool:
  name: RestAPI-Service-vm-pool

steps:
- checkout: self
  displayName: 'Checkout code'

- script: mvn -version
  displayName: 'Show Maven and Java version'

- script: mvn clean install
  displayName: 'Build project'

- script: mvn test -Dcucumber.filter.tags=@initial
  displayName: 'Run @initial tests'