parameters:
  - name: cucumberName
    type: string
    default: 'Teil1'

trigger:
  branches:
    include:
      - main
      - demo_with_yml

pool:
  name: RestAPI-Service-vm-pool

variables:
  TEST_PROJECT_PATH: '$(Pipeline.Workspace)/Playwright Java Cucumber'


steps:
  - checkout: self
    displayName: 'Checkout code'

  - script: mvn --version
    displayName: 'Show Maven and Java version'

  - script: mvn clean install -DskipTests
    displayName: 'Build project'

  - script: |
      echo "Running tests where scenario name matches: ${{ parameters.cucumberName }}"
      mvn test "-Dcucumber.plugin=json:target/cucumber-report.json" "-Dcucumber.filter.name=.*${{ parameters.cucumberName }}.*"
    displayName: 'Run Cucumber tests (with JSON report)'

  - script: |
      echo Testprojektpfad: %TEST_PROJECT_PATH%
    displayName: 'Show TEST_PROJECT_PATH variable'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/target/cucumber-report.json'
      artifact: 'cucumber-json-report'
      publishLocation: 'pipeline'
    displayName: 'Publish Cucumber JSON Report'